### ISSUE TITLE
Create Java spike with JPA

### ISSUE THREAD

**Issue by massfords** [massfords/we99#1]
Create sample project w/ Java using the domain model

**Comment by massfords** [comment]
Just pushed my spike here:

created a new branch named "spike/jpa"

**Comment by massfords** [comment]
Documented on the wiki

**Comment by orchieboy** [comment]
Very nice!! A lot of work,  the structure is all there. 
I like how you've id's the CRUD services we need for the plating. You've though that through a lot further that I have. You've put a lot of time in here you should totally take the lead on this if you want to.
