### ISSUE TITLE
Create sample project w/ Grails using the existing data model

### ISSUE THREAD

**Issue by orchieboy** [massfords/we99#2]

**Comment by orchieboy** [comment]
Uploaded a sample grails app to load a simple JSON PlateTemplate into the database

https://github.com/orchieboy/GrailsSpike.git

**Comment by massfords** [comment]
Nice job. I'm not surprised that there's not a lot of code here. Seems like Grails does a good job with convention over config. I'm sorry to report that the JPA spike took closer to 8 hours than my original 4, but I also took it a bit further than I had originally planned. 

I'll try out this grails project later today. In the meantime, could you review the wiki page I put up and see if there are any gaps in the grails from what I documented there?
